export const INITIAL_PLACES = [
  {
    id: "plc-srinagar-dal",
    name: "Dal Lake & Houseboats",
    district: "Srinagar",
    category: "Tourism",
    description: "The jewel of Srinagar, spanning 18 sq km with traditional wood-carved houseboats, floating vegetable markets, and serene Shikara rides framed by the Zabarwan mountains.",
    lat: 34.0837,
    lng: 74.8372,
    bestTime: "April to October (Spring to Autumn) & Snow Season (Jan-Feb)",
    openingHours: "Open 24/7 (Shikaras operate 6:00 AM - 9:00 PM)",
    officialWebsite: "https://jk-tourism.gov.in",
    seasonalInfo: "Shikara rides in morning mist; frozen margins during Chilla-i-Kalan (Jan).",
    nearbyAttractions: JSON.stringify(["Mughal Gardens", "Shankaracharya Hill", "Nigeen Lake", "Hazratbal Shrine"]),
    imageUrl: "https://images.pexels.com/photos/25786569/pexels-photo-25786569.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "plc-gulmarg-gondola",
    name: "Gulmarg Ski Resort & Gondola",
    district: "Baramulla",
    category: "Skiing",
    description: "World-famous ski destination at 2,650m elevation featuring Asia's highest cable car (Gondola) ascending to Apharwat Peak at 4,390m.",
    lat: 34.0484,
    lng: 74.3805,
    bestTime: "December to March for Skiing; May to September for Meadows & Trekking",
    openingHours: "Gondola: 10:00 AM - 5:00 PM (Subject to weather & wind)",
    officialWebsite: "https://www.gulmarggondola.com",
    seasonalInfo: "Heavy powdery snow Jan-Feb; alpine wildflowers June-August.",
    nearbyAttractions: JSON.stringify(["Apharwat Peak", "Kongdoori", "St. Mary's Church", "Strawberry Valley", "Drung Waterfall"]),
    imageUrl: "https://images.pexels.com/photos/26054717/pexels-photo-26054717.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "plc-pahalgam-baisaran",
    name: "Pahalgam & Betaab Valley",
    district: "Anantnag",
    category: "Nature",
    description: "The Valley of Shepherds on the banks of the Lidder River, famous for pine forests, Baisaran 'Mini Switzerland', Aru Valley, and Betaab Valley.",
    lat: 34.0162,
    lng: 75.3150,
    bestTime: "March to November (Best for trout fishing, trekking, and family stays)",
    openingHours: "Betaab & Aru Parks: 8:00 AM - 6:00 PM",
    officialWebsite: "https://anantnag.nic.in",
    seasonalInfo: "Pristine green meadows in summer; golden pine reflection in October.",
    nearbyAttractions: JSON.stringify(["Baisaran Valley", "Aru Valley", "Chandanwari", "Lidder River Rafting", "Mamleshwar Temple"]),
    imageUrl: "https://images.pexels.com/photos/7743323/pexels-photo-7743323.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "plc-sonamarg-thajiwas",
    name: "Sonamarg & Thajiwas Glacier",
    district: "Ganderbal",
    category: "Tourism",
    description: "'Meadow of Gold' located at 2,740m on the Srinagar-Leh highway. Famous for Thajiwas Glacier, Sindh River, and gateway to Great Lakes Trek.",
    lat: 34.3023,
    lng: 75.2938,
    bestTime: "April to October (Roads usually open around April)",
    openingHours: "Open day time; glacier pony rides operate 7:00 AM - 6:00 PM",
    officialWebsite: "https://ganderbal.nic.in",
    seasonalInfo: "Glacier remains snow-bound even in peak summer July.",
    nearbyAttractions: JSON.stringify(["Thajiwas Glacier", "Zojila Pass", "Zero Point", "Vishansar Lake", "Sindh River"]),
    imageUrl: "https://images.pexels.com/photos/6478192/pexels-photo-6478192.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "plc-srinagar-tulip",
    name: "Indira Gandhi Memorial Tulip Garden",
    district: "Srinagar",
    category: "Heritage",
    description: "Asia's largest tulip garden situated on the foothills of Zabarwan Range overlooking Dal Lake, home to over 1.5 million tulips in 60+ varieties.",
    lat: 34.0890,
    lng: 74.8720,
    bestTime: "Late March to Mid-April (Annual Tulip Festival)",
    openingHours: "9:00 AM - 7:00 PM during bloom season",
    officialWebsite: "https://jk-tourism.gov.in",
    seasonalInfo: "Opens exclusively for ~30 days in Spring each year.",
    nearbyAttractions: JSON.stringify(["Botanical Garden", "Pari Mahal", "Nishat Bagh", "Chashme Shahi"]),
    imageUrl: "https://images.pexels.com/photos/25786569/pexels-photo-25786569.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "plc-anantnag-verinag",
    name: "Verinag Spring & Mughal Garden",
    district: "Anantnag",
    category: "Heritage",
    description: "The primary source of the Jhelum River, enclosed by an octagonal stone basin and Mughal arcade constructed by Emperor Jahangir in 1620 AD.",
    lat: 33.5350,
    lng: 75.2520,
    bestTime: "April to October",
    openingHours: "8:00 AM - 6:30 PM",
    officialWebsite: "https://anantnag.nic.in",
    seasonalInfo: "Crystal turquoise water year-round surrounding royal lawns.",
    nearbyAttractions: JSON.stringify(["Achabal Mughal Garden", "Kokernag Botanical Garden", "Martand Sun Temple"]),
    imageUrl: "https://images.pexels.com/photos/7743323/pexels-photo-7743323.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "plc-kupwara-bangus",
    name: "Bangus Valley & Lolab",
    district: "Kupwara",
    category: "Nature",
    description: "An untouched biosphere in North Kashmir with expansive sub-alpine meadows, dense pine woodlands, and pristine crystal streams.",
    lat: 34.3712,
    lng: 74.1200,
    bestTime: "May to September",
    openingHours: "Sunrise to Sunset",
    officialWebsite: "https://kupwara.nic.in",
    seasonalInfo: "Lush wildflower carpets and traditional nomadic Gujjar seasonal settlements.",
    nearbyAttractions: JSON.stringify(["Lolab Valley", "Kalaroos Caves", "Seemab Valley"]),
    imageUrl: "https://images.pexels.com/photos/6478192/pexels-photo-6478192.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "plc-gurez-dawar",
    name: "Gurez Valley (Dawar & Habba Khatoon)",
    district: "Bandipora",
    category: "Tourism",
    description: "Remote high-altitude valley along the Kishenganga River, dominated by the pyramid-shaped Habba Khatoon Peak and traditional log homes.",
    lat: 34.6333,
    lng: 74.8333,
    bestTime: "June to September (Razdan Pass remains snowbound in winter)",
    openingHours: "Daylight hours (Check district advisory at Razdan Pass)",
    officialWebsite: "https://bandipore.nic.in",
    seasonalInfo: "Access via Razdan Pass (3,557m). Ideal for camping, trout fishing, and eco-tourism.",
    nearbyAttractions: JSON.stringify(["Habba Khatoon Peak", "Kishenganga River", "Tulail Valley", "Razdan Pass"]),
    imageUrl: "https://images.pexels.com/photos/26054717/pexels-photo-26054717.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "plc-badgam-doodhpathri",
    name: "Doodhpathri (Valley of Milk)",
    district: "Badgam",
    category: "Nature",
    description: "A tranquil alpine resort with roaring white streams cascading over boulders in green sloping pastures surrounded by dense deodar forests.",
    lat: 33.8820,
    lng: 74.5610,
    bestTime: "May to October",
    openingHours: "8:00 AM - 7:00 PM",
    officialWebsite: "https://budgam.nic.in",
    seasonalInfo: "Cool fresh breeze, horse riding, and peaceful picnic spots near Shaliganga river.",
    nearbyAttractions: JSON.stringify(["Yusmarg", "Shaliganga River", "Tosamaidan"]),
    imageUrl: "https://images.pexels.com/photos/25786569/pexels-photo-25786569.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "plc-doda-bhaderwah",
    name: "Bhaderwah (Mini Kashmir)",
    district: "Doda",
    category: "Nature",
    description: "Nestled in the Chenab Valley, Bhaderwah offers rolling meadows like Jai Valley, Padri Pass, and ancient Vasuki Nag temples.",
    lat: 32.9790,
    lng: 75.7130,
    bestTime: "April to November",
    openingHours: "Open 24/7",
    officialWebsite: "https://doda.nic.in",
    seasonalInfo: "Paragliding in Jai Valley and snow play at Padri Pass in early spring.",
    nearbyAttractions: JSON.stringify(["Jai Valley", "Padri Pass", "Chinta Valley", "Kailash Kund"]),
    imageUrl: "https://images.pexels.com/photos/6478192/pexels-photo-6478192.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  }
];

export const INITIAL_BUSINESSES = [
  {
    id: "biz-ahdoos",
    name: "Ahdoos Restaurant & Hotel",
    category: "Restaurant",
    district: "Srinagar",
    location: "Residency Road, Lal Chowk",
    address: "Residency Road, Near Jehangir Chowk, Srinagar, J&K 190001",
    phone: "+91 194 247 2593",
    email: "info@ahdooshotel.com",
    website: "https://ahdooshotel.com",
    openingHours: "12:00 PM - 10:30 PM",
    services: JSON.stringify(["Authentic Wazwan", "Rogan Josh", "Rista", "Gushtaba", "Bakery", "Private Dining"]),
    rating: 4.8,
    totalReviews: 342,
    priceRange: "$$$",
    imageUrl: "https://images.pexels.com/photos/7743323/pexels-photo-7743323.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "biz-sukoon-houseboat",
    name: "Sukoon Heritage Houseboat",
    category: "Houseboat",
    district: "Srinagar",
    location: "Nigeen Lake",
    address: "Kabutar Khana, Nigeen Lake, Srinagar, J&K 190003",
    phone: "+91 194 242 1234",
    email: "stay@sukoonhouseboat.com",
    website: "https://sukoonhouseboat.com",
    openingHours: "24 Hours Front Desk",
    services: JSON.stringify(["Luxury Wood Carved Suites", "Eco-friendly Wastewater Treatment", "Shikara Transfers", "Kashmiri Kahwa Tea", "Sundeck View"]),
    rating: 4.9,
    totalReviews: 189,
    priceRange: "$$$$",
    imageUrl: "https://images.pexels.com/photos/7743323/pexels-photo-7743323.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "biz-khyber-resort",
    name: "The Khyber Himalayan Resort & Spa",
    category: "Hotel",
    district: "Baramulla",
    location: "Gulmarg",
    address: "Climatological Station, Gulmarg, J&K 193403",
    phone: "+91 195 425 4666",
    email: "reservations@khyberresorts.com",
    website: "https://khyberresorts.com",
    openingHours: "24 Hours Check-in",
    services: JSON.stringify(["5-Star Luxury Suites", "Heated Swimming Pool", "L'Occitane Spa", "Ski Storage & Rentals", "Heated Floors"]),
    rating: 4.9,
    totalReviews: 520,
    priceRange: "$$$$",
    imageUrl: "https://images.pexels.com/photos/26054717/pexels-photo-26054717.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "biz-suffi-bakery",
    name: "Suffi Traditional Kandur Bakery",
    category: "Bakery",
    district: "Anantnag",
    location: "Main Chowk, Anantnag",
    address: "Kazi Bagh Road, Main Market, Anantnag, J&K 192101",
    phone: "+91 94190 12345",
    email: "contact@suffibakery.com",
    website: "",
    openingHours: "5:30 AM - 8:00 PM",
    services: JSON.stringify(["Kashmiri Girda Bread", "Tsot & Katlam", "Sheermal", "Kulcha", "Fresh Noon Chai"]),
    rating: 4.7,
    totalReviews: 95,
    priceRange: "$",
    imageUrl: "https://images.pexels.com/photos/25786569/pexels-photo-25786569.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "biz-chai-jaai",
    name: "Chai Jaai Tea Room",
    category: "Cafe",
    district: "Srinagar",
    location: "Maharaja Bazar / Bund Srinagar",
    address: "1st Floor, Mahatta & Co., The Bund, Residency Road, Srinagar 190001",
    phone: "+91 194 245 0012",
    email: "chaijaai@kashmirtea.com",
    website: "https://chaijaai.com",
    openingHours: "10:30 AM - 8:30 PM",
    services: JSON.stringify(["Authentic Pink Noon Chai", "Saffron Kahwa", "Keema Samovar Snacks", "Kashmiri Art Decor"]),
    rating: 4.8,
    totalReviews: 280,
    priceRange: "$$",
    imageUrl: "https://images.pexels.com/photos/25786569/pexels-photo-25786569.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "biz-kashmir-crafts-emp",
    name: "Kashmir Arts & Pashmina Cottage",
    category: "Handicrafts & Pashmina",
    district: "Srinagar",
    location: "Polo View Market",
    address: "Polo View High Street, Lal Chowk, Srinagar 190001",
    phone: "+91 194 248 8890",
    email: "pashmina@kashmircrafts.in",
    website: "https://kashmircrafts.in",
    openingHours: "10:00 AM - 8:00 PM",
    services: JSON.stringify(["100% Certified Pashmina Shawls", "Kani Shawls", "Hand-knotted Silk Carpets", "Paper Mache Artifacts", "GI Tag Verification"]),
    rating: 4.9,
    totalReviews: 210,
    priceRange: "$$$",
    imageUrl: "https://images.pexels.com/photos/7743323/pexels-photo-7743323.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "biz-airport-cab-union",
    name: "Srinagar Airport Tourist Taxi Service",
    category: "Transport / Taxi",
    district: "Srinagar",
    location: "Srinagar International Airport (SXR)",
    address: "Arrivals Terminal Taxi Counter, Sheikh ul-Alam Airport, Srinagar 190007",
    phone: "+91 194 230 0230",
    email: "cab@srinagarairporttaxi.com",
    website: "https://srinagarairporttaxi.com",
    openingHours: "24 Hours (Synced with Flight Arrivals)",
    services: JSON.stringify(["Fixed Government Tariff Cabs", "4WD Snow Chain Cabs for Gulmarg", "Pahalgam & Sonamarg Transfers", "Airport Pickup"]),
    rating: 4.6,
    totalReviews: 430,
    priceRange: "$$",
    imageUrl: "https://images.pexels.com/photos/6478192/pexels-photo-6478192.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  },
  {
    id: "biz-skims-hospital",
    name: "Sher-i-Kashmir Institute of Medical Sciences (SKIMS)",
    category: "Hospital & Health",
    district: "Srinagar",
    location: "Soura, Srinagar",
    address: "SKIMS Main Campus, Soura, Srinagar, J&K 190011",
    phone: "+91 194 240 1013",
    email: "director@skims.ac.in",
    website: "https://skims.ac.in",
    openingHours: "24/7 Emergency & Trauma Care",
    services: JSON.stringify(["24/7 Emergency Unit", "Cardiology & Altitude Care", "Trauma Center", "Blood Bank", "Pharmacy"]),
    rating: 4.5,
    totalReviews: 150,
    priceRange: "$",
    imageUrl: "https://images.pexels.com/photos/26054717/pexels-photo-26054717.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    verified: true,
  }
];

export const INITIAL_EVENTS = [
  {
    id: "evt-tulip-fest-2025",
    title: "Indira Gandhi Memorial Tulip Festival 2025",
    category: "Festival",
    district: "Srinagar",
    location: "Tulip Garden, Zabarwan Foothills, Srinagar",
    startDate: "2025-03-25",
    endDate: "2025-04-20",
    description: "Annual Spring celebration marking the bloom of 1.5 million tulips with Kashmiri folk music, Saz-e-Kashmir performances, and local food popups.",
    organizer: "J&K Tourism Department",
    contact: "1800-180-7193",
    imageUrl: "https://images.pexels.com/photos/25786569/pexels-photo-25786569.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    status: "upcoming",
  },
  {
    id: "evt-gulmarg-winter-fest",
    title: "Gulmarg Winter Snow Sports Carnival",
    category: "Sports",
    district: "Baramulla",
    location: "Gulmarg Ski Slopes & Apharwat Base",
    startDate: "2025-02-10",
    endDate: "2025-02-28",
    description: "National ski championship, snowboarding competitions, night skiing, ice sculpture exhibition, and winter music concerts.",
    organizer: "J&K Winter Sports Association",
    contact: "+91 195 425 4444",
    imageUrl: "https://images.pexels.com/photos/26054717/pexels-photo-26054717.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    status: "ongoing",
  },
  {
    id: "evt-saffron-festival",
    title: "Pampore Saffron Harvest Celebration",
    category: "Cultural",
    district: "Pulwama",
    location: "Saffron Fields, Pampore",
    startDate: "2025-10-20",
    endDate: "2025-11-05",
    description: "Experience purple saffron crocus fields harvesting, participate in saffron plucking, visit authentic saffron drying setups, and taste pure Saffron Kahwa.",
    organizer: "Department of Agriculture J&K",
    contact: "+91 193 322 1100",
    imageUrl: "https://images.pexels.com/photos/7743323/pexels-photo-7743323.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    status: "upcoming",
  },
  {
    id: "evt-craft-expo",
    title: "Kashmir Artisans & Handicraft Heritage Expo",
    category: "Exhibition",
    district: "Srinagar",
    location: "Kashmir Haat (Exhibition Ground), Srinagar",
    startDate: "2025-05-01",
    endDate: "2025-05-15",
    description: "Live demonstration by master artisans of Kani shawl weaving, Paper Mache, Wood Carving, Khatamband ceiling work, and authentic GI certified selling.",
    organizer: "Directorate of Handicrafts & Handloom",
    contact: "+91 194 247 2000",
    imageUrl: "https://images.pexels.com/photos/25786569/pexels-photo-25786569.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    status: "upcoming",
  }
];

export const INITIAL_TRANSPORT = [
  {
    id: "trp-air-gulmarg",
    mode: "Private Cab / Shared Taxi",
    fromLocation: "Srinagar Airport (SXR)",
    toLocation: "Gulmarg",
    distanceKm: 56,
    approxTime: "1 hour 45 min",
    estimatedFare: "₹2,200 - ₹2,800 (Sedan/Innova); Shared Sumo: ₹200/seat from Parimpora",
    operatingHours: "6:00 AM - 8:00 PM",
    contactInfo: "+91 194 230 0230 (Airport Taxi Union)",
    tips: "During heavy snowfall in Tangmarg (12 km before Gulmarg), 2WD vehicles stop and you must transfer to 4WD cabs with snow tire chains (Standard govt rate ₹1,000 round trip)."
  },
  {
    id: "trp-air-pahalgam",
    mode: "Private Cab / Shared Sumo",
    fromLocation: "Srinagar Airport (SXR)",
    toLocation: "Pahalgam",
    distanceKm: 92,
    approxTime: "2 hours 30 min",
    estimatedFare: "₹2,800 - ₹3,500 (Private Cab); Shared Sumo from Pantha Chowk: ₹250/seat",
    operatingHours: "5:30 AM - 7:00 PM",
    contactInfo: "+91 193 624 3228 (Pahalgam Taxi Stand)",
    tips: "Route passes through Pampore saffron fields and Sangam (famous for Kashmiri willow cricket bat workshops)."
  },
  {
    id: "trp-shikara-tariff",
    mode: "Shikara",
    fromLocation: "Ghat 1 - 24 (Dal Lake)",
    toLocation: "Floating Market / Houseboats / Char Chinar",
    distanceKm: 5,
    approxTime: "1 - 2 hours",
    estimatedFare: "Govt Fixed Rate: ₹770 per hour (per boat, up to 4 passengers)",
    operatingHours: "6:00 AM - 9:30 PM",
    contactInfo: "Tourist Reception Centre (TRC) Srinagar",
    tips: "Always check official Tariff Chart displayed at Ghats. Early morning 6 AM ride to Floating Vegetable Market is highly recommended."
  },
  {
    id: "trp-gondola-ticket",
    mode: "Gondola Cable Car",
    fromLocation: "Gulmarg Base Station",
    toLocation: "Kongdoori (Phase 1) & Apharwat Peak (Phase 2)",
    distanceKm: 5,
    approxTime: "15 min per phase",
    estimatedFare: "Phase 1: ₹740/person; Phase 2: ₹950/person",
    operatingHours: "10:00 AM - 4:30 PM",
    contactInfo: "https://www.gulmarggondola.com",
    tips: "Tickets MUST be booked online weeks in advance at the official J&K Cable Car website to avoid touts or sold-out slots."
  },
  {
    id: "trp-train-banihal",
    mode: "Srinagar Banihal Express Train",
    fromLocation: "Srinagar Railway Station (Nowgam)",
    toLocation: "Banihal / Anantnag / Baramulla",
    distanceKm: 120,
    approxTime: "1 hour 40 min to Banihal",
    estimatedFare: "₹45 - ₹120 (Regular / Vande Bharat Express)",
    operatingHours: "7:00 AM - 7:30 PM",
    contactInfo: "Indian Railways IRCTC App",
    tips: "Punctual, economical, and scenic ride across paddy fields and snow-capped mountain backdrop."
  }
];

export const INITIAL_WEATHER = [
  {
    id: "wtr-srinagar",
    district: "Srinagar",
    tempC: 4,
    condition: "Partly Cloudy",
    humidity: 78,
    windKmh: 8,
    snowChance: 20,
    advisory: "Chilly morning breeze. Moderate thermal layer & Pheran or jacket required.",
    seasonContext: "Winter transition into late winter. Early morning frost on Dal Lake margins.",
  },
  {
    id: "wtr-gulmarg",
    district: "Gulmarg",
    tempC: -5,
    condition: "Snowing",
    humidity: 89,
    windKmh: 18,
    snowChance: 85,
    advisory: "Fresh snowfall expected (15-25cm). Heavy winter gear, snow boots, and 4WD vehicles required.",
    seasonContext: "Peak Ski Season. Snow depth at Apharwat Peak is currently ~2.2 meters.",
  },
  {
    id: "wtr-pahalgam",
    district: "Pahalgam",
    tempC: -1,
    condition: "Snow Showers",
    humidity: 82,
    windKmh: 12,
    snowChance: 60,
    advisory: "Light snowfall along Lidder river banks. Carry waterproof coats and thermals.",
    seasonContext: "Winter pine woodland setting. River Lidder flowing steadily.",
  },
  {
    id: "wtr-sonamarg",
    district: "Sonamarg",
    tempC: -7,
    condition: "Heavy Snow",
    humidity: 92,
    windKmh: 22,
    snowChance: 90,
    advisory: "Sub-zero conditions. Road status via Gagangeer tunnel subject to BRO clearing.",
    seasonContext: "Thajiwas glacier covered under deep snow blanket.",
  },
  {
    id: "wtr-anantnag",
    district: "Anantnag",
    tempC: 5,
    condition: "Clear",
    humidity: 70,
    windKmh: 6,
    snowChance: 10,
    advisory: "Pleasant sunny afternoon, sharp drop in temperature after 5 PM.",
    seasonContext: "Clear views of Verinag and Mattan springs.",
  },
  {
    id: "wtr-kupwara",
    district: "Kupwara",
    tempC: 2,
    condition: "Foggy",
    humidity: 85,
    windKmh: 5,
    snowChance: 30,
    advisory: "Dense morning fog across Lolab valley road network. Drive with fog lights.",
    seasonContext: "Winter morning haze over pine ridges.",
  }
];

export const INITIAL_ARTICLES = [
  {
    id: "art-wazwan-guide",
    title: "Understanding Kashmiri Wazwan: The 36-Course Royal Culinary Art",
    category: "Food & Cuisine",
    summary: "Wazwan is not just a meal; it is a master craft passed through generations of Vasta Waza (master chefs).",
    content: "The meal begins with washing hands in a copper bowl called 'Tash-t-Nari'. Guests sit in groups of four around a large copper platter called 'Traem'. Key signature dishes include Rista (spiced meatball in saffron red gravy), Rogan Josh (tender lamb cooked with Kashmiri red chillies and cockscomb flower color), Tabak Maaz (crispy fried ribs), Gushtaba (velvety white yogurt meatball - the grand finale), and Yakhni (fragrant curd-based gravy with mint and fennel).",
    sources: "Department of Culture J&K, Kashmir Culinary Academy",
    language: "en"
  },
  {
    id: "art-pashmina-buyer-guide",
    title: "How to Identify Authentic 100% Cashmere Pashmina",
    category: "Shopping Guide",
    summary: "Essential tips to protect yourself against machine-made acrylic or polyester imitations when buying shawls in Kashmir.",
    content: "1. Look for the Official GI Tag (Geographical Indication) QR code label certified by CDI Srinagar. 2. Real hand-spun Pashmina has an irregular organic weave texture under light, whereas machine synthetic looks completely uniform plastic. 3. The Ring Test: A real fine Pashmina shawl glides smoothly through a standard wedding ring. 4. Burn Test: Real Pashmina (Capra Hircus goat hair) burns like human hair with an earthy organic ash, whereas synthetic melts into hard plastic beads.",
    sources: "Crafts Development Institute (CDI) Srinagar",
    language: "en"
  },
  {
    id: "art-winter-seasons-kashmir",
    title: "The 3 Winter Seasons of Kashmir: Chilla-i-Kalan, Khurd, and Bacha",
    category: "Culture & Etiquette",
    summary: "How locals navigate the traditional winter calendar that shapes life in the Kashmir valley.",
    content: "Kashmiri winter is divided into three distinct phases: 1. **Chilla-i-Kalan** (Dec 21 - Jan 31): 40 days of extreme intense cold when water pipes freeze, snow is deepest, and Kangri (earthen firepot inside Pheran) is indispensable. 2. **Chilla-i-Khurd** (Feb 1 - Feb 20): 20 days of moderate winter with frequent snow bursts. 3. **Chilla-i-Bacha** (Feb 21 - Mar 2): 10 days of minor winter leading into the arrival of Spring blossoms.",
    sources: "Kashmir Cultural Heritage Trust",
    language: "en"
  }
];
